### ISSUE TITLE
How to define props with defaults partially

### ISSUE THREAD

**Issue by IAmRGroot** [antfu/unplugin-vue2-script-setup#101]
Hi, I'm not sure if this is the right place, but let me know if it is not.

I have the following component setup:
![image](https://user-images.githubusercontent.com/8398505/149953297-bd9b01d9-b0e1-48d9-90fc-9778169297c2.png)

And I use it like this:
![image](https://user-images.githubusercontent.com/8398505/149953364-8e4ad14a-e4e3-404d-b96d-b3b92095d772.png)

I'm getting the following TS error: 
`Type '{ value: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<__VLS_DefinePropsToOptions<Props>>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>'.
  Property 'label' is missing in type '{ value: string; }' but required in type 'Omit<Readonly<ExtractPropTypes<__VLS_DefinePropsToOptions<Props>>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>'.`

I would have thought that the withDefaults would allow me to omit the label property. It seems to be working fine, with the error there, but I would like the error removed.

Am I missing some syntax or am I misunderstanding the withDefaults?

I have a repo setup here https://github.com/IAmRGroot/script-setup-typed-props

**Comment by xiaoxiangmoe** [comment]
It's volar's bug.

see https://github.com/johnsoncodehk/volar/issues/868

**Comment by xiaoxiangmoe** [comment]
fixed in v0.31.1
