### ISSUE TITLE
Custom directives

### ISSUE THREAD

**Issue by manniL** [antfu/unplugin-vue2-script-setup#104]
Hey 👋🏻

I was wondering whether custom directives are supported inside the `<script setup>` tag.
From my current test it seems they are not but I might do sth. wrong 🤔

Example component:

```vue
<script setup>
// enables v-focus in templates
const vFocus = {
  mounted: (el) => el.focus()
}
</script>
1
<template>
  <input v-focus />
</template>
```

**UPDATE**

Seems that `const focus = {}` works but `const vFocus = {}`  does not.

**Comment by xiaoxiangmoe** [comment]
Try move vFocus to another file and import this.
