### ISSUE TITLE
在setup语法中使用pinia语法报错

### ISSUE THREAD

**Issue by yanbowe** [antfu/unplugin-vue2-script-setup#119]
vue-cli  vue2集成pinia  运行可以用 打包报错
![60c025bd75d27439e6c9e5b0a878899](https://user-images.githubusercontent.com/43030980/154874533-23617a42-bf40-4914-aed9-9f1ca7532720.png)
![a42ba2c3b6db16c67363a9c51955b3a](https://user-images.githubusercontent.com/43030980/154874536-e970e7a5-0616-4f0a-9832-de273f6f20b2.png)
![19806c930f477e9874b9c05a0f030ac](https://user-images.githubusercontent.com/43030980/154874540-2fdb7f95-f9e1-4409-b282-cfe8b0a0b71e.png)

**Comment by xiaoxiangmoe** [comment]
能提供一个最小可复现的 demo 吗？

**Comment by yanbowe** [comment]
> 能提供一个最小可复现的 demo 吗？

https://github.com/yanbowe/pz-vu2-vueCli
本地正常运行，打包后运行报错

**Comment by xiaoxiangmoe** [comment]
看起来有点奇怪，我先查查 QAQ

**Comment by xiaoxiangmoe** [comment]
You should add `parallel: false,  // disable thread-loader, which is not compactible with this plugin` in your `vue.config.js`.

**Comment by xiaoxiangmoe** [comment]
duplicated to https://github.com/antfu/unplugin-vue2-script-setup/issues/49

**Comment by yanbowe** [comment]
> See [README.md #install ##VueCLI](https://github.com/antfu/unplugin-vue2-script-setup#install)
> 
> You should add `parallel: false` in your `vue.config.js`. Because thread-loader is not compactible with this plugin.

谢谢，可以正常运行了
