### ISSUE TITLE
vue-cli-service build  :  "export 'default' (imported as 'mod') was not found in

### ISSUE THREAD

**Issue by duguangyan** [antfu/unplugin-vue2-script-setup#125]
生产环境构建才出现的问题    vue-cli-service build   "export 'default' (imported as 'mod') was not found in 
使用  vue-cli-service build --mode xxx  这种就没问题

**Comment by xiaoxiangmoe** [comment]
Can you provide a minimal reproduction?

**Comment by duguangyan** [comment]
{
  "name": "xxx",
  "version": "1.0.1",
  "description": "xxx",
  "author": "xx",
  "license": "MIT",
  "scripts": {
    "dev": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "build:prod": "vue-cli-service build --mode prod",
    "build:sit": "vue-cli-service build --mode sit",
    "build:uat": "vue-cli-service build --mode uat",
    "preview": "node build/index.js --preview",
    "lint": "eslint --ext .js,.vue src",
    "test:unit": "jest --clearCache && vue-cli-service test:unit",
    "test:ci": "npm run lint && npm run test:unit",
    "svgo": "svgo -f src/icons/svg --config=src/icons/svgo.yml",
    "new": "plop"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,vue}": [
      "eslint --fix",
      "git add"
    ]
  },
  "keywords": [
    "vue",
    "admin",
    "dashboard",
    "element-ui",
    "boilerplate",
    "admin-template",
    "management-system"
  ],
  "repository": {
    "type": "git",
    "url": "https://gitee.com/y_project/RuoYi-Vue.git"
  },
  "dependencies": {
    "@riophae/vue-treeselect": "0.4.0",
    "@vue/composition-api": "^1.2.4",
    "axios": "0.18.1",
    "clipboard": "2.0.4",
    "default-passive-events": "^1.0.10",
    "echarts": "4.2.1",
    "echarts-liquidfill": "^2.0.6",
    "element-ui": "2.13.0",
    "file-saver": "^2.0.1",
    "fuse.js": "3.4.4",
    "js-beautify": "^1.10.2",
    "js-cookie": "2.2.0",
    "jsencrypt": "3.0.0-rc.1",
    "lodash": "^4.17.15",
    "mathjs": "^9.5.1",
    "moment": "^2.24.0",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "path-to-regexp": "2.4.0",
    "qrcodejs2": "^0.0.2",
    "screenfull": "4.2.0",
    "stompjs": "^2.3.3",
    "unplugin-vue2-script-setup": "^0.6.11",
    "vue": "2.6.10",
    "vue-count-to": "1.0.13",
    "vue-cropper": "0.4.9",
    "vue-print-nb": "^1.5.0",
    "vue-quill-editor": "^3.0.6",
    "vue-router": "3.0.2",
    "vue-splitpane": "1.0.4",
    "vuedraggable": "2.20.0",
    "vuex": "3.1.0",
    "webpack-virtual-modules": "^0.4.3",
    "xlsx": "^0.15.6"
  },
  "devDependencies": {
    "@babel/core": "7.0.0",
    "@babel/parser": "^7.7.4",
    "@babel/register": "7.0.0",
    "@vue/cli-plugin-babel": "3.5.3",
    "@vue/cli-plugin-eslint": "^3.9.1",
    "@vue/cli-plugin-unit-jest": "3.5.3",
    "@vue/cli-service": "3.5.3",
    "@vue/test-utils": "1.0.0-beta.29",
    "autoprefixer": "^9.5.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "10.0.1",
    "babel-jest": "23.6.0",
    "chalk": "2.4.2",
    "chokidar": "2.1.5",
    "compression-webpack-plugin": "^5.0.1",
    "connect": "3.6.6",
    "eslint": "5.15.3",
    "eslint-plugin-vue": "5.2.2",
    "html-webpack-plugin": "3.2.0",
    "http-proxy-middleware": "^0.19.1",
    "husky": "1.3.1",
    "lint-staged": "8.1.5",
    "mockjs": "1.0.1-beta3",
    "node-sass": "^4.9.0",
    "plop": "2.3.0",
    "runjs": "^4.3.2",
    "sass-loader": "^7.1.0",
    "script-ext-html-webpack-plugin": "2.1.3",
    "script-loader": "^0.7.2",
    "serve-static": "^1.13.2",
    "svg-sprite-loader": "4.1.3",
    "svgo": "1.2.0",
    "vue-template-compiler": "2.6.10"
  },
  "engines": {
    "node": ">=8.9",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}

**Comment by duguangyan** [comment]
"unplugin-vue2-script-setup": "^0.6.11",

**Comment by xiaoxiangmoe** [comment]
兄弟，你给个最小可复现的仓库，让我能在本地跑起来，我才能知道发生了啥啊🤔

**Comment by duguangyan** [comment]
非常感谢支持，将^0.6.11 升级到 ^0.9.3  
根据最新 vue cli 文档
// vue.config.js
const ScriptSetup = require('unplugin-vue2-script-setup/webpack').default

module.exports = {
  parallel: false,  // disable thread-loader, which is not compactible with this plugin
  configureWebpack: {
    plugins: [
      ScriptSetup({ /* options */ }),
    ],
  },
}
修改即可
