### ISSUE TITLE
typescript TS7006 TS2339 error

### ISSUE THREAD

**Issue by ylucifer** [antfu/unplugin-vue2-script-setup#130]
generated code:

import { ref } from "@vue/composition-api";
const __sfc_main = {};
// TS7006 TS2339 error
__sfc_main.setup = (__props, __ctx) => {
   // ....
};
export default __sfc_main;

---------------------------------------------------

expect code:

import { ref } from "@vue/composition-api";
const __sfc_main = {} as any;
__sfc_main.setup = (__props : any, __ctx : any) => {
	// ....
};
export default __sfc_main;

I don't know how to config this plugin execute after ts-loader

**Comment by xiaoxiangmoe** [comment]
Please disable type checking. See

https://github.com/antfu/unplugin-vue2-script-setup/blob/55f5753ed3ca6883d9abac1d3ff1c3d2216e8243/examples/vue-cli/vue.config.cjs#L17
