### ISSUE TITLE
import  script setup component  Module  has no default export.

### ISSUE THREAD

**Issue by 634323580** [antfu/unplugin-vue2-script-setup#131]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/12928893/161382595-0eca9990-42b5-4220-8fb2-83d233d60b3d.png">
<img width="521" alt="image" src="https://user-images.githubusercontent.com/12928893/161382972-21835a9a-9a9b-4bc5-be06-062bebe498e2.png">

**Comment by jddao** [comment]
+1

**Comment by BobbyJonas** [comment]
+1

**Comment by xiaoxiangmoe** [comment]
Can you provide a minimal reproduction?

**Comment by BobbyJonas** [comment]
nuxt 2 + typescript without using nuxt bridge
`buildModules` param in nuxt.config.ts is like
```
  buildModules: [
    "@nuxtjs/stylelint-module",
    "@nuxtjs/tailwindcss",
    "@nuxt/postcss8",
    "@nuxtjs/composition-api/module",
    "@nuxt/typescript-build",
    ["@nuxtjs/dotenv", { path: "./" }],
  ],
```

And when i import the child component (written in vue `setup` syntax) in the parent component,
the nuxt builtin `fork-ts-checker-webpack-plugin` typescript check would throw out an error as below

```
ERROR in src/pages/chatroom/:id.vue:23:8
TS1192: Module '"/Users/gewb/workspace/my-stream-fe/src/components/chatroom/PrimarySidebar.vue"' has no default export.
    21 | 
    22 | import MainContent from "~/components/chatroom/MainContent.vue";
  > 23 | import PrimarySidebar from "~/components/chatroom/PrimarySidebar.vue";
```

**Comment by BobbyJonas** [comment]
related issue: [#668 of fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/668)
