### ISSUE TITLE
defineProps is not defined with ESbuild

### ISSUE THREAD

**Issue by KevinBerthier** [antfu/unplugin-vue2-script-setup#136]
I moved from webpack to ESbuild but I get `ReferenceError: defineProps is not defined`

My config is a bit different from the doc :
`plugins: [rails(), vuePlugin(), require('unplugin-vue2-script-setup/esbuild').default()],`
instead of 
`plugins: [rails(), vuePlugin(), require('unplugin-vue2-script-setup/esbuild')()],`

**Comment by xiaoxiangmoe** [comment]
try `plugins: [rails(), require('unplugin-vue2-script-setup/esbuild').default(), vuePlugin(), ],`

**Comment by KevinBerthier** [comment]
@xiaoxiangmoe I get :
```bash
✘ [ERROR] The JSX syntax extension is not currently enabled

    apps/notification-center/NotificationCenter.vue:1:0:
      1 │ <template>
        ╵ ^

  The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able
  to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.
```

Here is my config :

```js
const config = {
  absWorkingDir: path.join(process.cwd(), 'app/javascript'),
  bundle: true,
  chunkNames: 'chunks/[name]-[hash]',
  entryPoints,
  format: 'esm',
  minify: process.env.RAILS_ENV == 'production',
  metafile: true,
  outdir: path.join(process.cwd(), 'app/assets/builds'),
  platform: 'browser',
  plugins: [rails(), require('unplugin-vue2-script-setup/esbuild').default(), vuePlugin()],
  sourcemap: process.env.RAILS_ENV != 'production',
  splitting: true,
  treeShaking: true,
  loader: {
    '.svg': 'dataurl'
  }
}
```

**Comment by xiaoxiangmoe** [comment]
Can you provide a minimal reproducible repo

**Comment by KevinBerthier** [comment]
@xiaoxiangmoe here it is https://github.com/KevinBerthier/unplugin-vue2-script-setup-esbuild-bug

**Comment by xiaoxiangmoe** [comment]
@sxzz Can you help to fix this?

**Comment by sxzz** [comment]
> @sxzz Can you help to fix this?

OK, I'll check it later.

**Comment by sxzz** [comment]
It seems to be a problem with `unplugin` or `esbuild-vue`, I'll try to fix it later.

**Comment by sxzz** [comment]
We need to wait for ESBUILD to resolve this issue https://github.com/evanw/esbuild/issues/1902

**Comment by sxzz** [comment]
Maybe you can use this plugin https://github.com/nativew/esbuild-plugin-pipe

**Comment by sxzz** [comment]
I wrote a plugin [esbuild-plugin-transform](https://github.com/sxzz/esbuild-plugin-transform). You can try this.
