### ISSUE TITLE
Error on bound SVG attributes

### ISSUE THREAD

**Issue by jaredmcateer** [antfu/unplugin-vue2-script-setup#137]
It seems that there is a problem detecting that `Ref<string>` is compatible with the `Numbish` type in the `@vue/runtime-dom`. 

![image](https://user-images.githubusercontent.com/781540/165556321-bb75fb31-ca7b-4567-b9df-73da1808cabc.png)

Minimal test case:

```vue
<script setup lang="ts">
import { ref } from "@vue/composition-api";
// `Numberish` in @vue/runtime-dom is `string | number` so these should work
const width = ref("100%");
const height = ref(100);
</script>

<template>
  <svg :width="width" :height="height"></svg>
</template>
```
Error produced:
```
Type 'Ref<string>' is not assignable to type 'Numberish'.ts(2322)
runtime-dom.d.ts(917, 3): The expected type comes from property 'width' which is declared here on type 'ElementAttrs<SVGAttributes>'
```

Using the `defineComponent` method there is no error:

```vue
<script lang="ts">
import { defineComponent, ref } from "@vue/composition-api";

export default defineComponent({
  setup() {
    const width = ref("100%");
    const height = ref(100);
    return { width, height };
  },
});
</script>

<template>
  <svg :width="width" :height="height"></svg>
</template>
```

**Comment by xiaoxiangmoe** [comment]
try add this file

https://github.com/antfu/unplugin-vue2-script-setup/blob/main/examples/vue-cli/src/shims-vue.d.ts

**Comment by jaredmcateer** [comment]
Yes that resolves the issue, thanks. I hadn't looked at that example as we're not using vue-cli, just a home rolled webpack config.

**Comment by xiaoxiangmoe** [comment]
If you are using vite, you also need add this

https://github.com/antfu/unplugin-vue2-script-setup/blob/main/playground/src/shims-vue.d.ts#L1
