### ISSUE TITLE
Is it possible to use this plugin side by side with class components?

### ISSUE THREAD

**Issue by jschweighofer** [antfu/unplugin-vue2-script-setup#141]
Hey!

We need to rewrite our legacy code (Vue 2, Class components) to use the Composition API and your plugin for script setup.

Do you see any issues installing your plugin and using it on some SFCs, while others still work "the old way"? We do not mix class components with script setup.

Does this plugin just skip a SFC when there is no script setup used? We are using Vite.

Best regards

**Comment by xiaoxiangmoe** [comment]
If you do not use ref sugar, it will skip a sfc when no script setup used.

**Comment by jschweighofer** [comment]
Ok great, thanks for the fast reply!
