### ISSUE TITLE
Property 'addCount' does not exist on type '{}'.ts(2339)

### ISSUE THREAD

**Issue by syymo** [antfu/unplugin-vue2-script-setup#142]
自己 搭建环境 和 使用 https://github.com/antfu/unplugin-vue2-script-setup/tree/main/playground 都会出现同样问题

![image](https://user-images.githubusercontent.com/26571594/174970277-95cd9831-c11a-4d54-9194-6af83233a909.png)

**Comment by ljfass** [comment]
+1

**Comment by ljfass** [comment]
感谢

**Comment by WaynePluto** [comment]
感谢，就是修改下tsconfig.json
`
  "vueCompilerOptions": {
    "target": 2,
  },
`

**Comment by luzdealba** [comment]
The solution by @WaynePluto works.

That's because `experimentalCompatMode` has been deprecated, so `target` must be used instead.

The [Support Vue 2 template](https://github.com/antfu/unplugin-vue2-script-setup#support-vue-2-template) section on the doc should be updated accordingly.

Best!

**Comment by jzsn2018** [comment]
# https://github.com/jzsn2018/day-record/issues/10#issue-1377107454

**Comment by jzsn2018** [comment]
#issue-1377107454

**Comment by jzsn2018** [comment]
#1377107454
