### ISSUE TITLE
Add compatibility with Vue ^2.7.0

### ISSUE THREAD

**Issue by craigrileyuk** [antfu/unplugin-vue2-script-setup#144]
So with Vue 2.7.0, Vue now includes the Composition API and <script setup> support.

What it doesn't include, however, is support for reactivityTransform.

At the moment, using 2.7 with this plugin breaks because the plugin is expecting @vue/composition-api as a peer dependency.

Any way to make this work?

**Comment by antfu** [comment]
This plugin will not work with 2.7. For built-in `reactivityTransform` in 2.7, we still wait it to be stable in Vue 3.3 then we can backport it.

**Comment by xiaoxiangmoe** [comment]
Hi, @craigrileyuk @darren-outdev 

Due to https://github.com/vuejs/rfcs/discussions/369, Reactivity Transform has been dropped. So it seems to we should not use it any more.
