### ISSUE TITLE
uniapp小程序支持吗

### ISSUE THREAD

**Issue by weiminghaoo** [antfu/unplugin-vue2-script-setup#148]
### Clear and concise description of the problem

uniapp小程序，引用组件，不会在当前页面的.json中引用当前组件，这个有什么解决方案吗-

### Suggested solution

-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by xiaoxiangmoe** [comment]
这个问题可能得去 [uni-app](https://github.com/dcloudio/uni-app) 提 issue 了。找他们适配一下。

**Comment by weiminghaoo** [comment]
> 这个问题可能得去 [uni-app](https://github.com/dcloudio/uni-app) 提 issue 了。找他们适配一下。

😂好吧

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3748
