### ISSUE TITLE
类型“{}”上不存在属性“XXX”。ts(2339)

### ISSUE THREAD

**Issue by 642661520** [antfu/unplugin-vue2-script-setup#150]
### Describe the bug

只要使用了setup ，在 template 中 使用的数据会提示 类型“{}”上不存在属性“XXX”。ts(2339)
![image](https://user-images.githubusercontent.com/35099538/190995556-d4da085d-ee2e-43b8-91c2-b97d51b3fee4.png)

### Reproduction

<script lang="ts"> export default {   data() {     return {       a: 11111,     };   }, }; </script> <script setup lang="ts"> import { ref } from "@vue/composition-api"; const b = ref(1); </script>  <template>   <div>     <a href="https://vitejs.dev" target="_blank"       >{{ a }}       {{ b }}       <img src="/vite.svg" class="logo" alt="Vite logo" />     </a>     <a href="https://vuejs.org/" target="_blank">       <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />     </a>   </div> </template>  <style scoped> .logo {   height: 6em;   padding: 1.5em;   will-change: filter; } .logo:hover {   filter: drop-shadow(0 0 2em #646cffaa); } .logo.vue:hover {   filter: drop-shadow(0 0 2em #42b883aa); } </style>

### System Info

```Shell
vsCode
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Quan-HHH** [comment]
How did you solve it? QAQ
