### ISSUE TITLE
Question: Ref<string> cannot assign to string. ts(2322)

### ISSUE THREAD

**Issue by zouhangwithsweet** [antfu/unplugin-vue2-script-setup#19]
![image](https://user-images.githubusercontent.com/21095710/130601247-16d199a4-f364-4548-a229-69e8016945c0.png)

Is it a problem with my vscode settings?

Volar + VScode

**Comment by antfu** [comment]
For the context: https://github.com/antfu/unplugin-vue2-script-setup/blob/main/shims.d.ts

**Comment by zouhangwithsweet** [comment]
It works. Thanks. :)
