### ISSUE TITLE
Combine with options api ?

### ISSUE THREAD

**Issue by iToreTS** [antfu/unplugin-vue2-script-setup#20]
Before I start using this interesting module - do I have to rewrite all of my components to composition api ?
Or can I have just some components with composition api and leave some components with their existing v2 options api ?

And if I go for Typescript for my new components - can my old components still use .js even in the same application ?

I am using vue-cli by the way.

BR.

**Comment by antfu** [comment]
https://v3.vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script
