### ISSUE TITLE
[plugin:unplugin-vue2-script-setup] Unexpected token, expected "," (1:16)

### ISSUE THREAD

**Issue by Neophen** [antfu/unplugin-vue2-script-setup#22]
Hey i have the weirdest issue:

here's the component:
```
<script setup name="OnThisVoyage">
import { useOrganisationIdProp } from '../../composables/useRouteHelpers.js';
import { provideBaseCardState } from '../../features/useBaseCardState.js';
import Service from '../../classes/Service.js';

import CargoRow from './CargoRow.vue';

const props = defineProps({
  ...useOrganisationIdProp(),
  shipmentId: {
    type: [Number, String],
    required: true,
  },
});

const {
  setStateLoading,
  setStateIdle,
  setStateError,
  setStateNoData,
} = provideBaseCardState();

const cargoes = ref([]);

const fetchCargoes = () => {
  Service.organisation(props.organisationId)
    .shipment(props.shipmentId)
    .voyage()
    .index()
    .onStart(setStateLoading)
    .onSuccess(({ data }) => {
      cargoes.value = data.filter(
        (cargo) => cargo.shipping_id !== props.shipmentId
      );
      setStateIdle();
    })
    .onNoData(setStateNoData)
    .onError(setStateError);
};

onMounted(() => {
  fetchCargoes();
});
</script>

<template>
  <BaseCardWithState
    title="On this voyage"
    no-data-title="No other cargoes on this voyage."
    @retry="fetchCargoes"
  >
    <CargoRow
      v-for="{ cargo_key, shipping_id, commodity } in cargoes"
      :key="cargo_key"
      :shipment-id="shipping_id"
      :commodity="commodity"
      :organisation-id="organisationId"
    />
  </BaseCardWithState>
</template>
```

When trying to render this component vite throws an error:
```
[plugin:unplugin-vue2-script-setup] Unexpected token, expected "," (1:16)
/Users/mykolas/Documents/Projects/myg2-frontend/src/components/OrganisationShipments/OnThisVoyage.vue:1:16
1  |  <script setup name="OnThisVoyage">
   |                  ^
2  |  import { useOrganisationIdProp } from '../../composables/useRouteHelpers.js';
3  |  import { provideBaseCardState } from '../../features/useBaseCardState.js';
```
<img width="1044" alt="Screenshot 2021-08-25 at 10 27 05" src="https://user-images.githubusercontent.com/6092928/130745714-192963ef-05f4-4dab-bb63-9def842e9d11.png">

**Comment by Neophen** [comment]
Does anything come to mind? I'm trying to disable things on by one and see what causes the issue

**Comment by Neophen** [comment]
ok so the issue was ` v-for="{ cargo_key, shipping_id, commodity } in cargoes"`
changed it to ` v-for="item in cargoes"
and it works now....

**Comment by Neophen** [comment]
Noticed something weird, something is broken the way this plugin works with v-for
you can't have the word `link` anywher in the variable, 
e.g. `link` `prefixLink` `linkAppend` 
Threse will all break with the same issue as mentioned above.
Also if (not fully confirmed) if the name of the item starts with the same text `v-for="booking in bookings"` although it migh just be that i've missed some `link` in another variable.

```
<div v-for="(link, index) in links" :key="index" class="py-4 space-y-2">
```

**Comment by Neophen** [comment]
I could most likely try and do a pr if you point me in the right direction.

**Comment by antfu** [comment]
Thanks, I will have a look on this

**Comment by flavionn** [comment]
Hello. Im getting the same token error when using <template lang="pug">

unplugin-vue2-script-setup 0.6.4 version

if i remove v-for or v-if from template works even as pug.

if template is html works
