### ISSUE TITLE
typescript pure type define in [defineProps] with custom type lead to error

### ISSUE THREAD

**Issue by TrungRueta** [antfu/unplugin-vue2-script-setup#30]
Hi!

To day i tried implement plugin (v.0.5.4) into my nuxt project. i found a bug:

Follow [plugin's readme instruction](https://github.com/antfu/unplugin-vue2-script-setup#configurations) we had support `defineProps`.

Follow [Vue 3 script setup frc](https://v3.vuejs.org/api/sfc-script-setup.html#typescript-only-features) about typescript user, we can define props in component like:

```ts
const props = defineProps<{
  foo: string
  bar?: number
}>()
```

This example work with plugin , but when i try define prop with custom type:

```ts
// custom type
export interface DocVersion {
  version: number
}
```

```ts
// component

<script lang="ts" setup>
import { DocVersion } from '~/lib/doc/Doc'

const props = defineProps<{ version?: DocVersion }>()
</script>

<template>
  <div>
    {{ version }}
  </div>
</template>
```

i got error message on runtime:
```
[Vue warn]: Invalid prop type: "null" is not a constructor
```

After research vue3 rfc's document above i found that:
```
"In dev mode, the compiler will try to infer corresponding runtime validation from the types. For example here foo: String is inferred from the foo: string type. If the type is a reference to an imported type, the inferred result will be foo: null (equal to any type) since the compiler does not have information of external files."
```

In vue 2 env, `{ typeName: { type: null } }` is not a valid format. Component still working on runtime but error thown out. 

Can we have any workaround for now? 

Many thank for your plugin!
Trung.

---

Update:

I think for now, before smart authors update a fix, we can workaround by:

set Vue.config.silent = true to disable all warning. This will disable warning about type:null is not a constructor. Component still working ok in runtime.

My suggest to fix plugin is:
Plugin should compile defienProps + custom type to `type:Null` or `type: Object`. this will more correct and avoid mismatch.

---
update 2

Look like we also can bypass error like this:

```ts
const props = defineProps<{ version?: {} & DocVersion }>()
```

![image](https://user-images.githubusercontent.com/12226007/131471655-80f02b87-83b5-4345-9d02-5314c9a35194.png)

Thankyou!

**Comment by antfu** [comment]
From the Vue 3 doc:

> As of now, the type declaration argument must be one of the following to ensure correct static analysis:
> 
> - A type literal
> - A reference to an interface or a type literal in the same file
