### ISSUE TITLE
Typescript: Readme missing note about different between Vue3's template and Vue2's template type checking

### ISSUE THREAD

**Issue by TrungRueta** [antfu/unplugin-vue2-script-setup#32]
Hi!

In plugin's readme for now we missing note about setup compact mode for project to merge type checking template.

For now, after setup plugin and volar (vscode ext). when write template tag + v-for, it force to put key on same template tag:

![image](https://user-images.githubusercontent.com/12226007/131470444-8a0b24e2-d64d-4f35-a6a0-b0c8a5820bc1.png)

This because volar checking follow Vue3 guide. In Vue2 key must apply to all child tags of `<template />` tag, not itself.

To avoid this issue in Volar's document they has compact mode:

[Volar - setup vue 2](https://github.com/johnsoncodehk/volar#using) 

```json
// tsconfig.json
{
  "compilerOptions": {
    ...
  },
  "vueCompilerOptions": {
    "experimentalCompatMode": 2
  },
}
```

Im has not experience to creating PR on git, what i can do is raise issue and count of you guys :) . Hope my info i usefull.

Thank for plugin!

**Comment by antfu** [comment]
Thanks for noting! I am happy to have it noted in the docs. Maybe it's good for you to start getting familiar with making PR and to have proper credit for it. 👍
