### ISSUE TITLE
Typescript: accept Enum as plain object in template

### ISSUE THREAD

**Issue by TrungRueta** [antfu/unplugin-vue2-script-setup#35]
Hi!

version:  plugin v0.5.6 - nuxt 2.15.8 

When use typescript in project i usually use `enum` as safe way to store config values. With composition api setup function we can do like this without issue:

![image](https://user-images.githubusercontent.com/12226007/131994498-804289ec-de9c-4e6a-9e10-8faf9e56332a.png)
![image](https://user-images.githubusercontent.com/12226007/131994535-db6bab3f-02a4-452e-b4b5-13621f4ff571.png)

When use script setup , editor still accept write enum and pass to template, but in runtime it not actually foward enum to template :

![image](https://user-images.githubusercontent.com/12226007/131994654-22737bc9-a097-4534-aa25-76bf4cb2b7ef.png)
![image](https://user-images.githubusercontent.com/12226007/131994775-7fe87281-3a7b-4798-82cf-4e7b2753d0df.png)

can we update this part to accept enum as normal static plain object in template.

Thank you!

**Comment by Shinigami92** [comment]
Is this supported by Vue 3?

**Comment by TrungRueta** [comment]
@Shinigami92 Hi, i posted public repo here to demo use enum as plain object thought script setup on Vue v3

https://github.com/TrungRueta/vue3-test

this project created by vue-cli latest, with only vue 3 - typescript setup 

check file component: 
https://github.com/TrungRueta/vue3-test/blob/master/src/components/HelloWorld.vue
