### ISSUE TITLE
Why isn't `defineExpose` supported?

### ISSUE THREAD

**Issue by chearon** [antfu/unplugin-vue2-script-setup#38]
Wouldn't it be easy to parse the macro and add the ObjectProperties to the return value of the setup function? Or would that be different from Vue 3 in some way?

**Comment by antfu** [comment]
Because Vue 2 does not have the concept of `expose`. But I see your point and indeed we might be able to make an approximal approach here (while the functionality could not be equivalent.

PR welcome!

**Comment by chearon** [comment]
I see now... I wasn't aware of `expose` because it's [not documented](https://v3.vuejs.org/guide/composition-api-setup.html#context). So Vue 3 has separate contexts for rendering and a component's public API, but with Vue 2 those are the same. `@vue/composition-api` already manifests that distinction since everything returned from `setup` becomes public API, so I think it's reasonable to make `defineExposed` do that here, like you said... PR on the way!

**Comment by chearon** [comment]
Fixed in c73b288021a9906a94e590627cf56411d0bc7877
