### ISSUE TITLE
Request: update ref-macros.d.ts

### ISSUE THREAD

**Issue by TrungRueta** [antfu/unplugin-vue2-script-setup#42]
vue/ref-macros library has new update. file `ref-macros.d.ts` now has other version:

![image](https://user-images.githubusercontent.com/12226007/133190799-d7164165-ffd0-4d85-a1e2-695248dc0c38.png)

I would like to update this file, it will help fix a lot mismatch typescript type check, specially issue with union null|undefine.

I can create pr if you accept.

Thanks!
Trung

**Comment by antfu** [comment]
I am not sure what do you mean by updating this. If you find it's misaligned with vue-next, feel free to send PR. But from your screenshot I don't think it's a correct fix since we would need to import the types from `@vue/composition-api` instead of `@vue/runtime-core`.
