### ISSUE TITLE
使用该插件后，无法正常使用

### ISSUE THREAD

**Issue by kailong321200875** [antfu/unplugin-vue2-script-setup#47]
不是使用vue-cli，而是用webpack5搭建的，单独使用composition-api是没有问题的，引入
unplugin-vue2-script-setup之后，就无法正常使用了。

![image](https://user-images.githubusercontent.com/32283845/136647073-dde10fb0-e94c-460c-815d-8b0ce9ca00d0.png)

最小demo地址：https://github.com/kailong321200875/test-demo

**Comment by antfu** [comment]
It seems like you are not installing the plugin in your config, and you will need to remove `ForkTsCheckerWebpackPlugin` and use `vue-tsc`
