### ISSUE TITLE
 Error: Cannot find module 'unplugin-vue2-script-setup/webpack' 

### ISSUE THREAD

**Issue by duguangyan** [antfu/unplugin-vue2-script-setup#50]
![image](https://user-images.githubusercontent.com/23021374/136738584-addc6b47-619d-4993-9193-40810e02e261.png)

**Comment by antfu** [comment]
Consider upgrading your Node version to 14 or above

**Comment by duguangyan** [comment]
Thank you very much for the support provided by the plug-in author. After testing, upgrading to node12.22.6 + or 14.18.0 can solve this problem.
