### ISSUE TITLE
How can i order this plugin and eslint ?

### ISSUE THREAD

**Issue by Hyphon** [antfu/unplugin-vue2-script-setup#55]
when i use this plugin in vue-cli, it will throw some warnings like 
```
- example.vue
  warning Replace `;`  with `cr`       prettier/prettier
```
this means plugin compiles before eslint, so there are lots of unexpected warnings.
is there any solution can fix this ?

**Comment by antfu** [comment]
I'd suggest running ESLint as a separate command or on CI instead of embedded in your dev tools - your editor should already handle it for development.
