### ISSUE TITLE
"withDefaults" doesn't work on Nuxt

### ISSUE THREAD

**Issue by Ubugeeei** [antfu/unplugin-vue2-script-setup#60]
Hi, thank you for awesome plugin!
I want to use "withDefaults" on NuxtJS, but I got some errors.
The other functions of this plugin are working fine.

- Nuxt: v2.15.6
- @nuxtjs/compositino-api: v0.29.3
- unplugin-vue2-script-setup": 0.6.12"

ReferenceError: withDefaults is not defined on Nuxt
<img width="909" alt="スクリーンショット 2021-10-30 15 38 36" src="https://user-images.githubusercontent.com/71201308/139523347-af1ab495-29a6-4a9c-a484-8709c270e0a8.png">

on my editor, it looks to  fine.
![スクリーンショット 2021-10-30 15 44 58](https://user-images.githubusercontent.com/71201308/139523419-8ba7dac2-bf16-49ba-9292-da2905a1092a.png)
![スクリーンショット 2021-10-30 15 45 18](https://user-images.githubusercontent.com/71201308/139523422-dbfef3c1-67f9-406d-902e-e94442ad4f47.png)

**Comment by joel-wenzel** [comment]
Try assigning a const var to the withDefaults return

``` const props = withDefaults... ```

**Comment by Ubugeeei** [comment]
@joel-wenzel 
Oh! thanks! resolved :D
