### ISSUE TITLE
get error when i want to change the order of eslint and unplugin-vue2-script-setup

### ISSUE THREAD

**Issue by Sorryjjj** [antfu/unplugin-vue2-script-setup#67]
to solve this #55 , i try
vue.config.js
![image](https://user-images.githubusercontent.com/29476225/141305111-c57264f8-cdc6-4acd-80f1-2e9bbfdb129d.png)

it seems that can not find this plugin, so what is the right name of this plugin?
![image](https://user-images.githubusercontent.com/29476225/141305263-0c03cf82-28c4-407f-bd5d-8b5c51fb7084.png)

**Comment by antfu** [comment]
https://github.com/antfu/unplugin-vue2-script-setup/issues/55#issuecomment-948899431

I'd recommend running eslint on cli instead of the bundler.
