### ISSUE TITLE
How to get the type support from volar?

### ISSUE THREAD

**Issue by Darma1106** [antfu/unplugin-vue2-script-setup#71]
For example
```
<template>
  <div>
    <Test  />
  </div>
</template>

<script setup lang="ts">
import Test from './test.vue'
</script>
```

Volar can't  provide the props and emits' type support for component.

**Comment by xiaoxiangmoe** [comment]
@Darma1106 see https://github.com/xiaoxiangmoe/vue2-vuecli-demo

**Comment by Darma1106** [comment]
> @Darma1106 see https://github.com/xiaoxiangmoe/vue2-vuecli-demo

I see, but I use your configuration(tsconfig) in vite, it isn't work.
Can you provide a demo of vite.

**Comment by Darma1106** [comment]
> @Darma1106 see https://github.com/xiaoxiangmoe/vue2-vuecli-demo

thank you, i find the vite demo from your repositories
