### ISSUE TITLE
Named slots error introduced in 0.7.2

### ISSUE THREAD

**Issue by martinglover** [antfu/unplugin-vue2-script-setup#83]
Using named slots defined with `<template v-slot:slotName></template>` are throwing the error below 

`[vite] Internal server error: Codegen node is missing for element/if/for node. Apply appropriate transforms first.
  Plugin: unplugin-vue2-script-setup`

The shorthand does not throw the error `<template #slotName></template>`

unplugin-vue2-script-setup 0.7.2 and up are throwing the error

vue 2.6.11
vue/composition-api 1.4.1
vite 2.6.14

**Comment by xiaoxiangmoe** [comment]
@martinglover fixed in https://github.com/antfu/unplugin-vue2-script-setup/pull/82
