### ISSUE TITLE
Functional components in `setup script` compiler failed

### ISSUE THREAD

**Issue by ShineKidd** [antfu/unplugin-vue2-script-setup#87]
```vue
<script setup lang="tsx"
const Test = () => <span>hello</span>
</script>

<template>
  <Test />
</template>
```

Error: `Uncaught ReferenceError: Test is not defined`

**Comment by antfu** [comment]
Is this valid in Vue 3?

**Comment by ShineKidd** [comment]
yes

**Comment by xiaoxiangmoe** [comment]
So far, the easiest way is —— moving the jsx component `Test` to another tsx file and import it.

**Comment by ShineKidd** [comment]
For more convenient access variables in context, I wouldn't choose to do that

**Comment by xiaoxiangmoe** [comment]
@ShineKidd 

Can you use this?

```vue
<script lang="tsx">
const Test = () => <span>hello</span>
</script>
<script setup lang="tsx">
</script>

<template>
  <Test />
</template>
```

**Comment by xiaoxiangmoe** [comment]
Temporarily close this issue and wait for user feedback to reopen it.
