### ISSUE TITLE
script setup在transform后，终端eslint报错Extra semicolon

### ISSUE THREAD

**Issue by catNano** [antfu/unplugin-vue2-script-setup#90]
script setup的transform顺序有问题，代码应该在eslint校验后，再transform

**Comment by antfu** [comment]
I would not recommend using eslint at the building/bundling phase.

**Comment by catNano** [comment]
It is an error reported after Vue cli is started
![image](https://user-images.githubusercontent.com/42427796/147518675-a10673a0-ae1a-4d04-b82d-d91ba4e7b8c3.png)

**Comment by xiaoxiangmoe** [comment]
@catNano 你能给我一个最小可复现的 demo 吗？我看看怎么配。

**Comment by xiaoxiangmoe** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
